package com.payzo.backend.util;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class RibValidatorTest {

    /**
     * Three known-good RIBs generated by {@code RibGenerator.generate}. If any
     * of these stops validating, both ends of the algorithm have drifted apart.
     */
    @Test
    void isValid_acceptsKnownGoodRibs() {
        // 10 (STB) + 001 + accountSeq=1 → key computed by RibGenerator
        String stb = generated("10", "001", 1L);
        String biat = generated("08", "001", 42L);
        String zitouna = generated("25", "001", 999L);

        assertThat(RibValidator.isValid(stb)).isTrue();
        assertThat(RibValidator.isValid(biat)).isTrue();
        assertThat(RibValidator.isValid(zitouna)).isTrue();
    }

    @Test
    void isValid_rejectsBadChecksum() {
        // valid 18-digit prefix, deliberately wrong 2-digit key
        String good = generated("10", "001", 1L);
        String tamperedKey = good.substring(0, 18) + "00";
        // mod 97 == 0 only by accident; flip if it happens
        if (RibValidator.isValid(tamperedKey)) {
            tamperedKey = good.substring(0, 18) + "01";
        }
        assertThat(RibValidator.isValid(tamperedKey)).isFalse();
    }

    @Test
    void isValid_rejectsWrongLength() {
        assertThat(RibValidator.isValid("123")).isFalse();
        assertThat(RibValidator.isValid("1234567890123456789")).isFalse();   // 19 digits
        assertThat(RibValidator.isValid("123456789012345678901")).isFalse(); // 21 digits
    }

    @Test
    void isValid_rejectsNonNumeric() {
        assertThat(RibValidator.isValid("1234567890123456789X")).isFalse();
        assertThat(RibValidator.isValid("ABCDEFGHIJKLMNOPQRST")).isFalse();
    }

    @Test
    void isValid_rejectsNull() {
        assertThat(RibValidator.isValid(null)).isFalse();
    }

    @Test
    void isValid_toleratesWhitespace() {
        String good = generated("10", "001", 1L);
        String spaced = good.substring(0, 2) + " " + good.substring(2, 5)
                + " " + good.substring(5, 18) + " " + good.substring(18, 20);
        assertThat(RibValidator.isValid(spaced)).isTrue();
    }

    @Test
    void normalize_stripsAllWhitespace() {
        assertThat(RibValidator.normalize("10 001 1234567890123 45"))
                .isEqualTo("10001123456789012345");
        assertThat(RibValidator.normalize("  10001123456789012345  "))
                .isEqualTo("10001123456789012345");
    }

    @Test
    void extractNumericBankCode_returnsFirstTwo() {
        String good = generated("08", "001", 7L);
        assertThat(RibValidator.extractNumericBankCode(good)).isEqualTo("08");
    }

    @Test
    void extractBranchCode_returnsThreeAfterBank() {
        String good = generated("10", "002", 1L);
        assertThat(RibValidator.extractBranchCode(good)).isEqualTo("002");
    }

    @Test
    void formatDisplay_groupsAsBBAAANNNNNNNNNNNNN_CC() {
        String good = generated("10", "001", 1L);
        String formatted = RibValidator.formatDisplay(good);
        assertThat(formatted).matches("\\d{2} \\d{3} \\d{13} \\d{2}");
    }

    /**
     * Local helper mirroring {@code com.payzo.cbs.util.RibGenerator} since the
     * CBS module sits in a separate Maven artifact and isn't on this test
     * classpath. Same algorithm so any drift between backend validation and
     * CBS generation surfaces here.
     */
    private static String generated(String numericBankCode, String branchCode, long accountSeq) {
        String first18 = numericBankCode + branchCode + String.format("%013d", accountSeq);
        java.math.BigInteger n = new java.math.BigInteger(first18 + "00");
        int rem = n.mod(java.math.BigInteger.valueOf(97)).intValue();
        int key = (rem == 0) ? 0 : (97 - rem);
        return first18 + String.format("%02d", key);
    }
}
