package com.payzo.backend.domain.entity;

import com.payzo.backend.domain.enums.RiskLevel;
import com.payzo.backend.domain.enums.TransactionStatus;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

/** PayZo-side mirror of a P2P transfer carrying status, ML score, OTP confirmation time, and a balance snapshot taken at submit. */
@Entity
@Table(
    name = "transactions",
    indexes = {
        @Index(name = "idx_tx_client_id",   columnList = "client_id"),
        @Index(name = "idx_tx_status",      columnList = "status"),
        @Index(name = "idx_tx_created_at",  columnList = "created_at"),
        @Index(name = "idx_tx_source_bank", columnList = "source_bank_code"),
        @Index(name = "idx_tx_dest_bank",   columnList = "dest_bank_code")
    }
)
@Getter
@Setter
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /** e.g. TRX-20251215-A3F9K — generated by TransactionReferenceGenerator */
    @Column(nullable = false, unique = true, length = 50)
    private String reference;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "client_id", nullable = false)
    private Client client;

    @Column(name = "source_account_number", nullable = false, length = 50)
    private String sourceAccountNumber;

    @Column(name = "destination_account_number", nullable = false, length = 50)
    private String destinationAccountNumber;

    /** Denormalised from CBS so bank-status checks never require a CBS call */
    @Column(name = "source_bank_code", nullable = false, length = 10)
    private String sourceBankCode;

    @Column(name = "dest_bank_code", nullable = false, length = 10)
    private String destBankCode;

    @Column(name = "dest_client_cin", length = 8)
    private String destClientCin;

    @Column(nullable = false, precision = 15, scale = 2)
    private BigDecimal amount;

    @Column(length = 500)
    private String motif;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 40)
    private TransactionStatus status = TransactionStatus.PENDING_OTP;

    /** ML output — null before scoring step */
    @Column(name = "risk_score", precision = 5, scale = 4)
    private BigDecimal riskScore;

    /** null before scoring step */
    @Enumerated(EnumType.STRING)
    @Column(name = "risk_level", length = 10)
    private RiskLevel riskLevel;

    /** CBS balance snapshot taken at transfer initiation — ML feature oldbalanceOrg */
    @Column(name = "source_balance_before", precision = 15, scale = 2)
    private BigDecimal sourceBalanceBefore;

    /** CBS balance snapshot taken at transfer initiation — ML feature oldbalanceDest */
    @Column(name = "dest_balance_before", precision = 15, scale = 2)
    private BigDecimal destBalanceBefore;

    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /** Set when the sender confirmed the transfer OTP (status moved PENDING_OTP → PENDING_SCORING). */
    @Column(name = "otp_confirmed_at")
    private OffsetDateTime otpConfirmedAt;

    /** Set when CBS executes the debit/credit — null while pending */
    @Column(name = "executed_at")
    private OffsetDateTime executedAt;

    @PrePersist
    protected void onCreate() {
        OffsetDateTime now = OffsetDateTime.now();
        createdAt = now;
        updatedAt = now;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = OffsetDateTime.now();
    }
}
